---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name: ['apt-transport-https', 'ca-certificates']
    state: present

- name: Debian/Ubuntu | Add Elasticsearch GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    filename: 'elastic_repo'
    update_cache: true

- name: Debian/Ubuntu | Install Kibana
  apt:
    name: "kibana={{ elastic_stack_version }}"
    state: present
    cache_valid_time: 3600
  tags: install
