---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name: ['apt-transport-https', 'ca-certificates']
    state: present

- when: logstash_install_java
  block:
    - name: Debian/Ubuntu | Install OpenJDK 1.8
      apt: name=openjdk-8-jre state=present cache_valid_time=3600
      tags: install

- name: Debian/Ubuntu | Add Elasticsearch GPG key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Debian/Ubuntu | Install Elasticsearch repo
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    state: present
    filename: 'elastic_repo'

- name: Debian/Ubuntu | Install Logstash
  apt:
    name: "logstash=1:{{ elastic_stack_version }}-1"
    state: present
    update_cache: true
  tags: install

- name: Debian/Ubuntu | Checking if wazuh-manager is installed
  command: dpkg -l wazuh-manager
  register: wazuh_manager_check_deb
  when: logstash_input_beats == false
  args:
    warn: false

- name: Debian/Ubuntu | Add user logstash to group ossec
  user:
    name: logstash
    groups: ossec
    append: true
  when:
    - logstash_input_beats == false
    - wazuh_manager_check_deb.rc == 0
