---
- name: Debian/Ubuntu | Install apt-transport-https and ca-certificates
  apt:
    name: ['apt-transport-https', 'ca-certificates']
    state: present

- when: elasticsearch_install_java
  block:
    - name: Debian/Ubuntu | Install OpenJDK 1.8
      apt: name=openjdk-8-jre state=present cache_valid_time=3600
      tags: install

- name: Debian/Ubuntu | Add Elasticsearch GPG key.
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Debian/Ubuntu | Install Elastic repo
  apt_repository:
    state: present
    repo: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
    filename: 'elastic_repo'
    update_cache: true

- name: Debian/Ubuntu | Install Elasticsarch
  apt:
    name: "elasticsearch={{ elastic_stack_version }}"
    state: present
    cache_valid_time: 3600
  tags: install
