---
- when: elasticsearch_install_java
  block:
    - name: RedHat/CentOS/Fedora | Install OpenJDK 1.8
      yum: name=java-1.8.0-openjdk state=present
      register: oracle_java_task_rpm_installed
      tags: install

- name: RedHat/CentOS/Fedora | Install Elastic repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: true

- name: RedHat/CentOS/Fedora | Install Elasticsarch
  package: name=elasticsearch-{{ elastic_stack_version }} state=present
  when: not elasticsearch_install_java or oracle_java_task_rpm_installed is defined
  tags: install
